export interface GradeSystem {
  name: string;
  grades: string[];
  type: "route" | "boulder";
}

export const gradeSystems: Record<string, GradeSystem> = {
  // Route grading systems
  yds: {
    name: "YDS (Yosemite Decimal System)",
    type: "route",
    grades: [
      "5.0",
      "5.1",
      "5.2",
      "5.3",
      "5.4",
      "5.5",
      "5.6",
      "5.7",
      "5.8",
      "5.9",
      "5.10a",
      "5.10b",
      "5.10c",
      "5.10d",
      "5.11a",
      "5.11b",
      "5.11c",
      "5.11d",
      "5.12a",
      "5.12b",
      "5.12c",
      "5.12d",
      "5.13a",
      "5.13b",
      "5.13c",
      "5.13d",
      "5.14a",
      "5.14b",
      "5.14c",
      "5.14d",
      "5.15a",
      "5.15b",
      "5.15c",
      "5.15d",
    ],
  },
  french: {
    name: "French",
    type: "route",
    grades: [
      "1",
      "2",
      "3",
      "4a",
      "4b",
      "4c",
      "5a",
      "5b",
      "5c",
      "6a",
      "6a+",
      "6b",
      "6b+",
      "6c",
      "6c+",
      "7a",
      "7a+",
      "7b",
      "7b+",
      "7c",
      "7c+",
      "8a",
      "8a+",
      "8b",
      "8b+",
      "8c",
      "8c+",
      "9a",
      "9a+",
      "9b",
      "9b+",
      "9c",
      "9c+",
    ],
  },
  uiaa: {
    name: "UIAA",
    type: "route",
    grades: [
      "I",
      "II",
      "III",
      "IV",
      "V",
      "VI",
      "VII",
      "VIII",
      "IX",
      "X-",
      "X",
      "X+",
      "XI-",
      "XI",
      "XI+",
      "XII-",
      "XII",
      "XII+",
    ],
  },
  british: {
    name: "British (E Grade)",
    type: "route",
    grades: [
      "M",
      "D",
      "VD",
      "S",
      "HS",
      "VS",
      "HVS",
      "E1",
      "E2",
      "E3",
      "E4",
      "E5",
      "E6",
      "E7",
      "E8",
      "E9",
      "E10",
      "E11",
    ],
  },
  australian: {
    name: "Australian (Ewbank)",
    type: "route",
    grades: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
      "32",
      "33",
      "34",
      "35",
    ],
  },

  // Boulder grading systems
  v_scale: {
    name: "V-Scale (Vermin/Hueco)",
    type: "boulder",
    grades: [
      "VB",
      "V0",
      "V1",
      "V2",
      "V3",
      "V4",
      "V5",
      "V6",
      "V7",
      "V8",
      "V9",
      "V10",
      "V11",
      "V12",
      "V13",
      "V14",
      "V15",
      "V16",
      "V17",
    ],
  },
  font: {
    name: "Fontainebleau",
    type: "boulder",
    grades: [
      "3",
      "4",
      "4+",
      "5",
      "5+",
      "6A",
      "6A+",
      "6B",
      "6B+",
      "6C",
      "6C+",
      "7A",
      "7A+",
      "7B",
      "7B+",
      "7C",
      "7C+",
      "8A",
      "8A+",
      "8B",
      "8B+",
      "8C",
      "8C+",
      "9A",
      "9A+",
      "9B",
      "9B+",
      "9C",
    ],
  },
};

export const getGradeSystemsForType = (
  type: "route" | "boulder",
): Record<string, GradeSystem> => {
  return Object.fromEntries(
    Object.entries(gradeSystems).filter(([_, system]) => system.type === type),
  );
};

export const getGradeSystemForClimbType = (climbType: string): string => {
  switch (climbType) {
    case "boulder":
      return "v_scale";
    case "sport":
    case "trad":
    case "top rope":
    case "alpine":
    default:
      return "yds";
  }
};

export const getGradesForSystem = (system: string): string[] => {
  return gradeSystems[system]?.grades || gradeSystems.yds.grades;
};
