// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdvivwbjohsduptmxabh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkdml2d2Jqb2hzZHVwdG14YWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODk4MzcsImV4cCI6MjA2NDQ2NTgzN30.YUO7193MtvWtc-lGB2LtVwHXfMCGqmDgex-P35pUsao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);